viesion: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
          name: The first step
          command: |
            echo 'Hello World'
            echo $PWD
      - run:
          name: List All Files here
          command: ls -al
      - run:
          name: Node Js version
          command: node -v

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - build