viesion: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/app
    steps:
      - checkout
      - run: 
          name: print setting env
          command: |
            echo 'Docker container setup under' $PWD
            echo 'Node version' && node -v 
            echo 'Yarn version' && yarn -v
            printenv
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-package-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --forzen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-package-{{ checksum "yarn.lock" }}   
  build_and_deploy:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/app
    steps:  
      - restore_cache:
          name: Restore Yarna Cache
          key: yarn-package-{{ checksum "yarn.lock" }}
      - run:
          name: Build and Deploy
          command: |
            yarn run build && yarn run deploy

workflows:
  version: 2.1
  build:
    jobs:
      - setup
      - build_and_deploy:
          requires:
            - setup
  