viesion: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/app
    steps:
      - checkout
      - run: 
          name: print setting env
          command: |
          echo 'Docker container setup under' $PWD
          echo 'Node version' && node -v 
          echo 'Yarn version' && yarn -v
          printenv

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - setup
  